export const BEGINNER = 'BEGINNER';
export const INTERMEDIATE = 'INTERMEDIATE';
export const ADVANCED = 'ADVANCED';
export const BEGINNER_INTERMEDIATE = 'BEGINNER_INTERMEDIATE';
export const INTERMEDIATE_ADVANCED = 'INTERMEDIATE_ADVANCED';
export const BEGINNER_ADVANCED = 'BEGINNER_ADVANCED';
