/* eslint-disable react/prop-types */
'use client';
import './globals.css';
import React, { useState } from 'react';
import TextArea from '@/components/Ui/TextArea/TextArea';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }) {
  const [text, setText] = useState('');
  return (
    <html lang='fa' dir='rtl'>
      <body
        className={`flex h-screen items-center justify-center bg-surface-light font-main antialiased`}
      >
        <TextArea
          value={text}
          onChange={setText}
          fullWidth
          placeholder='نظرت رو بنویس'
          className='mx-16'
          rows={3}
          errorMessage='متن وارد شده اشتباه است'
          errorClassName='mr-20'
        />
        {children}
      </body>
    </html>
  );
}
