/* eslint-disable react/prop-types */
import { ThemeProvider } from '@/contexts/ThemeContext';
import './globals.css';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import React from 'react';
import { AuthProvider } from '@/contexts/AuthContext';
import prismadb from '@/libs/prismadb';
import { Toaster } from 'react-hot-toast';
import { headers } from 'next/headers';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  let user = null;
  if (session?.user?.userId) {
    user = await prismadb.user.findUnique({
      where: { id: session.user.userId },
    });
  }

  const requestHeaders = headers();
  const fullUrl = requestHeaders.get('referer');
  let currentPath = '/';
  if (fullUrl) {
    const url = new URL(fullUrl);
    currentPath = url.pathname;
  }
  const hideHeaderFooter = ['/login', '/signup', '/confirm-code'].includes(
    currentPath,
  );

  return (
    <ThemeProvider>
      <AuthProvider initialUser={user}>
        <html lang='fa' dir='rtl'>
          <body
            className={`flex flex-col bg-background-light font-main text-text-light antialiased dark:bg-background-dark dark:text-text-dark`}
          >
            {!hideHeaderFooter && <Header isLogin={session} />}
            {children}
            {!hideHeaderFooter && <Footer />}
            <Toaster />
          </body>
        </html>
      </AuthProvider>
    </ThemeProvider>
  );
}
