/* eslint-disable react/prop-types */
import { ThemeProvider } from '@/contexts/ThemeContext';
import './globals.css';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/app/api/auth/[...nextauth]/route';
import React from 'react';
import { AuthProvider } from '@/contexts/AuthContext';
import prismadb from '@/libs/prismadb';
import { Toaster } from 'react-hot-toast';
import dynamic from 'next/dynamic';
import VisitLogger from '@/components/modules/VisitorLogger/VisitorLogger';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// بارگذاری کامپوننت ClientSideAOS فقط در سمت کلاینت
const ClientSideAOS = dynamic(() => import('@/components/ClientSideAOS'), {
  ssr: false, // غیرفعال کردن رندر در سمت سرور
});

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  let user = null;

  if (session?.user?.userId) {
    try {
      // دریافت اطلاعات کاربر از پایگاه داده
      const rawUser = await prismadb.user.findUnique({
        where: { id: session.user.userId },
        include: {
          questions: true,
          comments: true,
          courses: true,
          carts: {
            include: {
              cartCourses: {
                include: {
                  course: {
                    select: {
                      id: true,
                      title: true,
                      cover: true,
                      shortAddress: true,
                    },
                  },
                },
              },
            },
          },
        },
      });

      // مدیریت مقدار null برای carts
      if (!rawUser) {
        console.warn('User not found in the database');
        user = null; // یا مقدار پیش‌فرض مناسب
      } else {
        user = {
          ...rawUser,
          carts: (rawUser.carts || []).map((cart) => {
            // استخراج فقط دوره‌ها از cartCourses
            const courses = cart.cartCourses.map(
              (cartCourse) => cartCourse.course,
            );

            const uniqueCourses = Array.from(
              new Map(courses.map((course) => [course.id, course])).values(),
            );

            return {
              ...cart,
              uniqueCourses, // اضافه کردن لیست دوره‌های یکتا
            };
          }),
        };
      }
    } catch (error) {
      console.error('Error fetching user data:', error.message);
      user = null; // مقدار پیش‌فرض در صورت بروز خطا
    }
  }

  return (
    <ThemeProvider>
      <AuthProvider initialUser={user}>
        <html lang='fa' dir='rtl'>
          <body
            className={`flex flex-col bg-background-light font-main text-text-light antialiased dark:bg-background-dark dark:text-text-dark`}
          >
            <VisitLogger />
            <ClientSideAOS />
            {children}
            <Toaster />
          </body>
        </html>
      </AuthProvider>
    </ThemeProvider>
  );
}
